# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy cases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  travelagency:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./travelagency

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    #- name: Install slidev
    #  run:  npm i -g @slidev/cli
    - name: Build
      run: npm run build -- --base SoftwareEngineeringBusinessCaseStudies
    - name: Deploy pages
      uses: crazy-max/ghaction-github-pages@v3
      with:
        build_dir: ./travelagency/dist
        target_branch: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
